name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Generate updated index.html
        run: |
          set -euo pipefail

          USER="Morkovka21Vek"
          DATE_HASH=$(date -u | sha256sum | cut -d ' ' -f1)
          REPOS_JSON=$(mktemp)

          curl -s "https://api.github.com/users/$USER/repos?per_page=100" > "$REPOS_JSON"

          PROJECT_BLOCKS=""

          while IFS= read -r repo; do
            name=$(echo "$repo" | jq -r '.name')
            desc=$(echo "$repo" | jq -r '.description // "No description"')
            fork=$(echo "$repo" | jq -r '.fork')

            if [[ "$fork" == "true" ]]; then
              continue
            fi

            image_url="https://opengraph.githubassets.com/$DATE_HASH/$USER/$name"

            PROJECT_BLOCKS+="
                <div class=\"projects-block\" id=\"$name\">
                  <div class=\"text-projects-block\">
                    <div class=\"timelinePoint\"></div>
                    <div class=\"timelineArrow\"></div>
                    <h3>$name</h3>
                    <h3>$desc</h3>
                    <div class=\"timelineArrowAfter\"></div>
                  </div>
                  <img alt=\"$name img preview\" class=\"projects-img\" src=\"$image_url\">
                </div>
          "
          done < <(jq -c '.[]' "$REPOS_JSON")

          mv index.html index_template.html
          sed "/<!-- Placeholder for Projects -->/{
              r /dev/stdin
              d
          }" index_template.html <<< "$PROJECT_BLOCKS" > index.html
          rm index_template.html

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:3.1.0
        with:
          add_suffix: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          clean: true
